## Downloading new data and adding season + physical variables to dataframe so new csv can be read in and ready to go in every notebook

In [1]:
import numpy as np
from oneargopy.OneArgo import Argo
from argopy import DataFetcher as ArgoDataFetcher
import pandas as pd
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import cartopy.feature as cfeature
import cmocean
import matplotlib.colors as mcolors
import matplotlib.dates as mdates
import matplotlib.cm as cm # new package for the colorbar
import matplotlib.patches as mpatches
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
from matplotlib.ticker import LogLocator, FormatStrFormatter
from matplotlib.colors import LogNorm
import gsw
import tarfile
import re
import glob

## SKIP TO CELL MARKED START HERE

In [2]:
argo = Argo('argo_config.json')

Starting initialize process...
Your current download settings are:
[DownloadSettings] ->
Base Directory: .,
Subdirectories: ['Index', 'Meta', 'Tech', 'Traj', 'Profiles'],
Index Files: ['ar_index_global_traj.txt', 'ar_index_global_tech.txt', 'ar_index_global_meta.txt', 'ar_index_global_prof.txt', 'argo_synthetic-profile_index.txt'],
Verbose Setting: True,
Max Attempts: 5,
Keep Index In Memory: True,
Float Type: bgc

Your current source settings are:
[Source Settings] ->
Hosts: ['https://data-argo.ifremer.fr/', 'https://usgodae.org/ftp/outgoing/argo/'],
Available Variables: None,
Data Assimilation Centers: None

Checking for subdirectories...
The Index directory already exists
The Meta directory already exists
The Tech directory already exists
The Traj directory already exists
The Profiles directory already exists

Downloading index files...
Updating ar_index_global_traj.txt...
Downloading ar_index_global_traj.txt from https://data-argo.ifremer.fr/ar_index_global_traj.txt.gz...
Unzipping ar_index_global_traj.txt.gz...
Success!
Updating ar_index_global_tech.txt...
Downloading ar_index_global_tech.txt from https://data-argo.ifremer.fr/ar_index_global_tech.txt.gz...
Unzipping ar_index_global_tech.txt.gz...
Success!
Updating ar_index_global_meta.txt...
Downloading ar_index_global_meta.txt from https://data-argo.ifremer.fr/ar_index_global_meta.txt.gz...
Unzipping ar_index_global_meta.txt.gz...
Success!
Updating ar_index_global_prof.txt...
Downloading ar_index_global_prof.txt from https://data-argo.ifremer.fr/ar_index_global_prof.txt.gz...
Unzipping ar_index_global_prof.txt.gz...
Success!
Updating argo_synthetic-profile_index.txt...
Downloading argo_synthetic-profile_index.txt from https://data-argo.ifremer.fr/argo_synthetic-profile_index.txt.gz...
Unzipping argo_synthetic-profile_index.txt.gz...
Success!

Transferring index files into dataframes...
Filling in source settings information...
Marking Parameters with their data mode...
Filling in source settings information...
Marking bgc floats in prof_index dataframe...
Creating float_stats dataframe...

20411 floats with 3390274 profiles found.
2930 BGC floats with 401022 profiles found.
Initialization is finished

In [19]:
#  same as line below but time = 2019-2020 and sensor = temp
# pressure = argo.select_profiles(lon_lim=[150,180], lat_lim=[-68,-58], type = 'bgc', sensor = 'CHLA') # all bgc floats within region

## New way of downloading data to avoid masked constant error

problem floats: 3902129, 6902814

Dataframe ran fine without the two floats above: they gave an "unsupported type for timedelta days component: MaskedConstant" error

In [4]:
# float ids from argo.select_profiles function for extended AAR region
float_ids = [1901135, 1901153, 1901155, 1901157, 1902662, 2901936, 2903454, 4903658, 5900345, 5901178, 5901645, 5901648, 5901698, 5901699, 5903242, 5903248, 5903260, 5903630, 5903717, 5903719, 5903720, 5903721, 5903722, 5903723, 5903939, 5904104, 5904105, 5904179, 5904481, 5904482, 5904483, 5904598, 5904599, 5904676, 5904677, 5904682, 5904688, 5905096, 5905097, 5905098, 5905099, 5905100, 5905101, 5905102, 5905103, 5905232, 5905372, 5905373, 5905374, 5905375, 5905376, 5905377, 5905379, 5905396, 5905555, 5905556, 5905557, 5905638, 5906207, 5906221, 5906442, 5906509, 5906581, 5906582, 5906583, 5906624, 6901004, 6902885, 6902891, 6903190, 6903233, 6903768, 6903777, 6990587, 7902154, 7902155, 7902379]

In [6]:
df = argo.load_float_data(float_ids, variables=['DOXY','TEMP','PSAL','CHLA', 'BBP700','NITRATE','PH_IN_SITU_TOTAL'])

Validating passed floats...
Validating passed 'variables'...
1901135_Sprof.nc does not need to be updated yet.
1901153_Sprof.nc does not need to be updated yet.
1901155_Sprof.nc does not need to be updated yet.
1901157_Sprof.nc does not need to be updated yet.
1902662_Sprof.nc does not need to be updated yet.
2901936_Sprof.nc does not need to be updated yet.
2903454_Sprof.nc does not need to be updated yet.
4903658_Sprof.nc does not need to be updated yet.
5900345_Sprof.nc does not need to be updated yet.
5901178_Sprof.nc does not need to be updated yet.
5901645_Sprof.nc does not need to be updated yet.
5901648_Sprof.nc does not need to be updated yet.
5901698_Sprof.nc does not need to be updated yet.
5901699_Sprof.nc does not need to be updated yet.
5903242_Sprof.nc does not need to be updated yet.
5903248_Sprof.nc does not need to be updated yet.
5903260_Sprof.nc does not need to be updated yet.
5903630_Sprof.nc does not need to be updated yet.
5903717_Sprof.nc does not need to be updated yet.
5903719_Sprof.nc does not need to be updated yet.
5903720_Sprof.nc does not need to be updated yet.
5903721_Sprof.nc does not need to be updated yet.
5903722_Sprof.nc does not need to be updated yet.
5903723_Sprof.nc does not need to be updated yet.
5903939_Sprof.nc does not need to be updated yet.
5904104_Sprof.nc does not need to be updated yet.
5904105_Sprof.nc does not need to be updated yet.
5904179_Sprof.nc does not need to be updated yet.
5904481_Sprof.nc does not need to be updated yet.
5904482_Sprof.nc does not need to be updated yet.
5904483_Sprof.nc does not need to be updated yet.
5904598_Sprof.nc does not need to be updated yet.
5904599_Sprof.nc does not need to be updated yet.
5904676_Sprof.nc does not need to be updated yet.
5904677_Sprof.nc does not need to be updated yet.
5904682_Sprof.nc does not need to be updated yet.
5904688_Sprof.nc does not need to be updated yet.
5905096_Sprof.nc does not need to be updated yet.
5905097_Sprof.nc does not need to be updated yet.
5905098_Sprof.nc does not need to be updated yet.
5905099_Sprof.nc does not need to be updated yet.
5905100_Sprof.nc does not need to be updated yet.
5905101_Sprof.nc does not need to be updated yet.
5905102_Sprof.nc does not need to be updated yet.
5905103_Sprof.nc does not need to be updated yet.
5905232_Sprof.nc does not need to be updated yet.
5905372_Sprof.nc does not need to be updated yet.
5905373_Sprof.nc does not need to be updated yet.
5905374_Sprof.nc does not need to be updated yet.
5905375_Sprof.nc does not need to be updated yet.
5905376_Sprof.nc does not need to be updated yet.
5905377_Sprof.nc does not need to be updated yet.
5905379_Sprof.nc does not need to be updated yet.
5905396_Sprof.nc does not need to be updated yet.
5905555_Sprof.nc does not need to be updated yet.
5905556_Sprof.nc does not need to be updated yet.
5905557_Sprof.nc does not need to be updated yet.
5905638_Sprof.nc does not need to be updated yet.
5906207_Sprof.nc does not need to be updated yet.
5906221_Sprof.nc does not need to be updated yet.
5906442_Sprof.nc does not need to be updated yet.
5906509_Sprof.nc does not need to be updated yet.
5906581_Sprof.nc does not need to be updated yet.
5906582_Sprof.nc does not need to be updated yet.
5906583_Sprof.nc does not need to be updated yet.
5906624_Sprof.nc does not need to be updated yet.
6901004_Sprof.nc does not need to be updated yet.
6902885_Sprof.nc does not need to be updated yet.
6902891_Sprof.nc does not need to be updated yet.
6903190_Sprof.nc does not need to be updated yet.
6903233_Sprof.nc does not need to be updated yet.
6903768_Sprof.nc does not need to be updated yet.
6903777_Sprof.nc does not need to be updated yet.
6990587_Sprof.nc does not need to be updated yet.
7902154_Sprof.nc does not need to be updated yet.
7902155_Sprof.nc does not need to be updated yet.
7902379_Sprof.nc does not need to be updated yet.
Loading float data...
WARNING: CHLA does not exist in File Profiles/1901135_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/1901135_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/1901135_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/1901135_Sprof.nc.
Loading Float data from float 1901135 with 173 profiles...
Dropping rows where no measurements were taken for 1901135...
WARNING: CHLA does not exist in File Profiles/1901153_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/1901153_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/1901153_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/1901153_Sprof.nc.
Loading Float data from float 1901153 with 309 profiles...
Dropping rows where no measurements were taken for 1901153...
WARNING: CHLA does not exist in File Profiles/1901155_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/1901155_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/1901155_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/1901155_Sprof.nc.
Loading Float data from float 1901155 with 355 profiles...
Dropping rows where no measurements were taken for 1901155...
WARNING: CHLA does not exist in File Profiles/1901157_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/1901157_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/1901157_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/1901157_Sprof.nc.
Loading Float data from float 1901157 with 322 profiles...
Dropping rows where no measurements were taken for 1901157...
WARNING: CHLA does not exist in File Profiles/1902662_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/1902662_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/1902662_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/1902662_Sprof.nc.
Loading Float data from float 1902662 with 92 profiles...
Dropping rows where no measurements were taken for 1902662...
WARNING: CHLA does not exist in File Profiles/2901936_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/2901936_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/2901936_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/2901936_Sprof.nc.
Loading Float data from float 2901936 with 187 profiles...
Dropping rows where no measurements were taken for 2901936...
Loading Float data from float 2903454 with 46 profiles...
Dropping rows where no measurements were taken for 2903454...
WARNING: NITRATE does not exist in File Profiles/4903658_Sprof.nc.
Loading Float data from float 4903658 with 150 profiles...
Dropping rows where no measurements were taken for 4903658...
WARNING: CHLA does not exist in File Profiles/5900345_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5900345_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5900345_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5900345_Sprof.nc.
Loading Float data from float 5900345 with 42 profiles...
Dropping rows where no measurements were taken for 5900345...
WARNING: CHLA does not exist in File Profiles/5901178_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5901178_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5901178_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5901178_Sprof.nc.
Loading Float data from float 5901178 with 213 profiles...
Dropping rows where no measurements were taken for 5901178...
WARNING: CHLA does not exist in File Profiles/5901645_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5901645_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5901645_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5901645_Sprof.nc.
Loading Float data from float 5901645 with 320 profiles...
Dropping rows where no measurements were taken for 5901645...
WARNING: CHLA does not exist in File Profiles/5901648_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5901648_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5901648_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5901648_Sprof.nc.
Loading Float data from float 5901648 with 324 profiles...
Dropping rows where no measurements were taken for 5901648...
WARNING: CHLA does not exist in File Profiles/5901698_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5901698_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5901698_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5901698_Sprof.nc.
Loading Float data from float 5901698 with 287 profiles...
Dropping rows where no measurements were taken for 5901698...
WARNING: CHLA does not exist in File Profiles/5901699_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5901699_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5901699_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5901699_Sprof.nc.
Loading Float data from float 5901699 with 313 profiles...
Dropping rows where no measurements were taken for 5901699...
WARNING: CHLA does not exist in File Profiles/5903242_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5903242_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5903242_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903242_Sprof.nc.
Loading Float data from float 5903242 with 206 profiles...
Dropping rows where no measurements were taken for 5903242...
WARNING: CHLA does not exist in File Profiles/5903248_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5903248_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5903248_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903248_Sprof.nc.
Loading Float data from float 5903248 with 373 profiles...
Dropping rows where no measurements were taken for 5903248...
WARNING: CHLA does not exist in File Profiles/5903260_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5903260_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5903260_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903260_Sprof.nc.
Loading Float data from float 5903260 with 369 profiles...
Dropping rows where no measurements were taken for 5903260...
WARNING: NITRATE does not exist in File Profiles/5903630_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903630_Sprof.nc.
Loading Float data from float 5903630 with 298 profiles...
Dropping rows where no measurements were taken for 5903630...
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903717_Sprof.nc.
Loading Float data from float 5903717 with 325 profiles...
Dropping rows where no measurements were taken for 5903717...
WARNING: CHLA does not exist in File Profiles/5903719_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5903719_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5903719_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903719_Sprof.nc.
Loading Float data from float 5903719 with 173 profiles...
Dropping rows where no measurements were taken for 5903719...
WARNING: CHLA does not exist in File Profiles/5903720_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5903720_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5903720_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903720_Sprof.nc.
Loading Float data from float 5903720 with 152 profiles...
Dropping rows where no measurements were taken for 5903720...
WARNING: CHLA does not exist in File Profiles/5903721_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5903721_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5903721_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903721_Sprof.nc.
Loading Float data from float 5903721 with 168 profiles...
Dropping rows where no measurements were taken for 5903721...
WARNING: CHLA does not exist in File Profiles/5903722_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5903722_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5903722_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903722_Sprof.nc.
Loading Float data from float 5903722 with 173 profiles...
Dropping rows where no measurements were taken for 5903722...
WARNING: CHLA does not exist in File Profiles/5903723_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5903723_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5903723_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903723_Sprof.nc.
Loading Float data from float 5903723 with 16 profiles...
Dropping rows where no measurements were taken for 5903723...
WARNING: CHLA does not exist in File Profiles/5903939_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5903939_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5903939_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5903939_Sprof.nc.
Loading Float data from float 5903939 with 204 profiles...
Dropping rows where no measurements were taken for 5903939...
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5904104_Sprof.nc.
Loading Float data from float 5904104 with 264 profiles...
Dropping rows where no measurements were taken for 5904104...
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5904105_Sprof.nc.
Loading Float data from float 5904105 with 183 profiles...
Dropping rows where no measurements were taken for 5904105...
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5904179_Sprof.nc.
Loading Float data from float 5904179 with 222 profiles...
Dropping rows where no measurements were taken for 5904179...
WARNING: CHLA does not exist in File Profiles/5904481_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5904481_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5904481_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5904481_Sprof.nc.
Loading Float data from float 5904481 with 232 profiles...
Dropping rows where no measurements were taken for 5904481...
WARNING: CHLA does not exist in File Profiles/5904482_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5904482_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5904482_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5904482_Sprof.nc.
Loading Float data from float 5904482 with 232 profiles...
Dropping rows where no measurements were taken for 5904482...
WARNING: CHLA does not exist in File Profiles/5904483_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5904483_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5904483_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5904483_Sprof.nc.
Loading Float data from float 5904483 with 262 profiles...
Dropping rows where no measurements were taken for 5904483...
WARNING: CHLA does not exist in File Profiles/5904598_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5904598_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5904598_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5904598_Sprof.nc.
Loading Float data from float 5904598 with 250 profiles...
Dropping rows where no measurements were taken for 5904598...
WARNING: CHLA does not exist in File Profiles/5904599_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5904599_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5904599_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5904599_Sprof.nc.
Loading Float data from float 5904599 with 243 profiles...
Dropping rows where no measurements were taken for 5904599...
Loading Float data from float 5904676 with 153 profiles...
Dropping rows where no measurements were taken for 5904676...
Loading Float data from float 5904677 with 167 profiles...
Dropping rows where no measurements were taken for 5904677...
Loading Float data from float 5904682 with 159 profiles...
Dropping rows where no measurements were taken for 5904682...
Loading Float data from float 5904688 with 159 profiles...
Dropping rows where no measurements were taken for 5904688...
WARNING: CHLA does not exist in File Profiles/5905096_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5905096_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5905096_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5905096_Sprof.nc.
Loading Float data from float 5905096 with 303 profiles...
Dropping rows where no measurements were taken for 5905096...
WARNING: CHLA does not exist in File Profiles/5905097_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5905097_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5905097_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5905097_Sprof.nc.
Loading Float data from float 5905097 with 320 profiles...
Dropping rows where no measurements were taken for 5905097...
WARNING: CHLA does not exist in File Profiles/5905098_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5905098_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5905098_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5905098_Sprof.nc.
Loading Float data from float 5905098 with 322 profiles...
Dropping rows where no measurements were taken for 5905098...
Loading Float data from float 5905099 with 151 profiles...
Dropping rows where no measurements were taken for 5905099...
Loading Float data from float 5905100 with 77 profiles...
Dropping rows where no measurements were taken for 5905100...
Loading Float data from float 5905101 with 3 profiles...
Dropping rows where no measurements were taken for 5905101...
Loading Float data from float 5905102 with 155 profiles...
Dropping rows where no measurements were taken for 5905102...
Loading Float data from float 5905103 with 157 profiles...
Dropping rows where no measurements were taken for 5905103...
WARNING: CHLA does not exist in File Profiles/5905232_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5905232_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5905232_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5905232_Sprof.nc.
Loading Float data from float 5905232 with 17 profiles...
Dropping rows where no measurements were taken for 5905232...
Loading Float data from float 5905372 with 157 profiles...
Dropping rows where no measurements were taken for 5905372...
Loading Float data from float 5905373 with 153 profiles...
Dropping rows where no measurements were taken for 5905373...
Loading Float data from float 5905374 with 61 profiles...
Dropping rows where no measurements were taken for 5905374...
Loading Float data from float 5905375 with 94 profiles...
Dropping rows where no measurements were taken for 5905375...
Loading Float data from float 5905376 with 100 profiles...
Dropping rows where no measurements were taken for 5905376...
Loading Float data from float 5905377 with 152 profiles...
Dropping rows where no measurements were taken for 5905377...
Loading Float data from float 5905379 with 149 profiles...
Dropping rows where no measurements were taken for 5905379...
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5905396_Sprof.nc.
Loading Float data from float 5905396 with 133 profiles...
Dropping rows where no measurements were taken for 5905396...
WARNING: NITRATE does not exist in File Profiles/5905555_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5905555_Sprof.nc.
Loading Float data from float 5905555 with 139 profiles...
Dropping rows where no measurements were taken for 5905555...
WARNING: NITRATE does not exist in File Profiles/5905556_Sprof.nc.
WARNING: PH_IN_SITU_TOTAL does not exist in File Profiles/5905556_Sprof.nc.
Loading Float data from float 5905556 with 147 profiles...
Dropping rows where no measurements were taken for 5905556...
WARNING: CHLA does not exist in File Profiles/5905557_Sprof.nc.
WARNING: BBP700 does not exist in File Profiles/5905557_Sprof.nc.
WARNING: NITRATE does not exist in File Profiles/5905557_Sprof.nc.

In [7]:
df.to_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new_unedited_bgc_profiles_BR_extended_area_all_time.csv', index = 'False')
# df.to_csv('/Users/steviewalker/Documents/IBIS_Project/Data_Summer/new_bgc_profiles_BR_extended_area_all_time.csv', index = 'False')

In [8]:
df = pd.read_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new_unedited_bgc_profiles_BR_extended_area_all_time.csv')

/var/folders/sr/nn_fjjln6s33md98tyfc3rd40000gn/T/ipykernel_42674/3263918958.py:1: DtypeWarning: Columns (0: LATITUDE, 1: LONGITUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new_unedited_bgc_profiles_BR_extended_area_all_time.csv')

## START HERE

## Using data Stevie downloaded with problem floats included (but they don't cause problems)

In [4]:
df = pd.read_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new2_bgc_profiles_BR_extended_area_all_time.csv')

/var/folders/sr/nn_fjjln6s33md98tyfc3rd40000gn/T/ipykernel_73723/1984743781.py:1: DtypeWarning: Columns (0: LATITUDE, 1: LONGITUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new2_bgc_profiles_BR_extended_area_all_time.csv')

## Convert to datetime, add month, year, season, MLP and physical variable columns (absolute salinity, conservative temperaure, potential density, in situ density, and buoyancy frequency

Might redo how MLP is calculated based on Terrats et al 2023 paper?

Datetime and latitude/longitude NaN values

In [5]:
# NEW DATA

#convert to datetime
df['DATE'] = pd.to_datetime(df['DATE'],format = 'mixed',utc=True)
df = df.dropna(subset=["DATE"]) #drop any cycles with no date or lat/lon 

#fix lat lon values with '--' (replace with nan) 
df['LATITUDE'] = pd.to_numeric(df['LATITUDE'], errors='coerce')
df['LONGITUDE'] = pd.to_numeric(df['LONGITUDE'], errors='coerce')

Month, year, and season column added

In [6]:
#create season columns
df["year"] = df["DATE"].dt.year.astype("Int64")
df["month"] = df["DATE"].dt.month.astype("Int64")

def assign_season(row):
    m = int(row["month"])
    y = int(row["year"])
    if m >= 9:
        return f"{y}-{y+1}"
    elif m <= 4:
        return f"{y-1}-{y}"
    else:
        return f"{y}"

df["season"] = df.apply(assign_season, axis=1)

Physical variable columns added (SA, CT, potential density, in-situ density, buoyancy frequency)

In [7]:
# define function for calculating SA, CT, potential dens, in-situ dens, buoyancy frequency
def calc_phys_vars(df):
        
    # Columns needed
    cols = ['PSAL_ADJUSTED','TEMP_ADJUSTED' ,'PRES_ADJUSTED', 'LATITUDE', 'LONGITUDE']
    
    # only do calculation on good qc T and S data - create nan values where not good data
    qc_flags = [1,2,5,8]
    mask_qc = df['PSAL_ADJUSTED_QC'].isin(qc_flags) & df['TEMP_ADJUSTED_QC'].isin(qc_flags)
    df['PSAL_ADJUSTED'] = df['PSAL_ADJUSTED'].where(mask_qc)
    df['TEMP_ADJUSTED'] = df['TEMP_ADJUSTED'].where(mask_qc)    
    
    # mask valid (non-null) rows
    mask = df[cols].notnull().all(axis=1)
    
    # initialize outputs as NaN
    SA = np.full(len(df), np.nan)
    CT = np.full(len(df), np.nan)
    rho = np.full(len(df), np.nan)
    sigma0 = np.full(len(df), np.nan)
    nsq = np.full(len(df), np.nan)
    
    # extract numeric arrays for valid rows
    SP = df.loc[mask, 'PSAL_ADJUSTED'].astype(float).to_numpy()
    PT = df.loc[mask, 'TEMP_ADJUSTED'].astype(float).to_numpy()
    pres = df.loc[mask, 'PRES_ADJUSTED'].astype(float).to_numpy()
    LAT = df.loc[mask, 'LATITUDE'].astype(float).to_numpy()
    LON = df.loc[mask, 'LONGITUDE'].astype(float).to_numpy()
    
    # calculate variables using gsw
    SA_valid = gsw.SA_from_SP(SP=SP, p=pres, lon=LON, lat=LAT)
    CT_valid = gsw.CT_from_t(SA=SA_valid, t=PT, p=pres)
    rho_valid = gsw.rho(SA=SA_valid, CT=CT_valid, p=pres)
    sigma0_valid = gsw.sigma0(SA=SA_valid, CT=CT_valid)
    nsq_valid = gsw.Nsquared(SA=SA_valid, CT=CT_valid, p=pres,lat=LAT)
    
    # store back into full-length arrays
    SA[mask] = SA_valid
    CT[mask] = CT_valid
    rho[mask] = rho_valid
    sigma0[mask] = sigma0_valid
    np.putmask(nsq, mask, nsq_valid) # found on stack overflow because nsq was 2 dimensional so previous method wasn't working
    
    # sdd results to the dataframe
    df = df.copy()
    df['SA'] = SA
    df['CT'] = CT
    df['rho'] = rho
    df['sigma0'] = sigma0
    df['nsq'] = nsq
    
    return df

df_edited = calc_phys_vars(df)

MLP column added - eventually change how it's calculated?

In [8]:
def calc_mlp_density(df_profile, delta_sigma=0.03):
    #calc MLD for a single profile using density threshold
    df_profile = df_profile.sort_values('PRES_ADJUSTED')

    # get SA, CT, and potential density values
    SA = df_profile['SA']
    CT = df_profile['CT']
    sigma0 = df_profile['sigma0']

    sigma_surface = sigma0.iloc[0]
    d_sigma = sigma0 - sigma_surface

    # find first depth where density difference exceeds threshold
    idx = np.argmax(d_sigma > delta_sigma)
    if d_sigma.iloc[idx] <= delta_sigma:
        return np.nan  # no threshold reached
    return df_profile['PRES_ADJUSTED'].iloc[idx]

mld = (df_edited.groupby(['WMOID', 'CYCLE_NUMBER']).apply(calc_mlp_density).reset_index(name='MLP'))
df_full_edited = df_edited.merge(mld, on=['WMOID', 'CYCLE_NUMBER'], how='left')

Save the dataframe with new columns added so you can just read in the csv in each notebook

In [9]:
df_full_edited.to_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/newest_bgc_profiles_ext_alltime.csv', index = 'False')

# df_full_edited.to_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new_bgc_profiles_BR_extended_area_all_time.csv', index = 'False')

In [10]:
df_full_edited

,Unnamed: 0,WMOID,CYCLE_NUMBER,DIRECTION,DATE,DATE_QC,LATITUDE,LONGITUDE,POSITION_QC,PRES,...,DOWNWELLING_PAR_ADJUSTED_ERROR,year,month,season,SA,CT,rho,sigma0,nsq,MLP
0,0,1901135,174,A,2013-08-23 01:13:44.999978+00:00,1,-62.0530,150.0250,1,6.10,...,NaN,2013,8,2013,34.084945,-1.831148,1027.374795,27.310568,1.905520e-08,97.00
1,1,1901135,174,A,2013-08-23 01:13:44.999978+00:00,1,-62.0530,150.0250,1,10.00,...,NaN,2013,8,2013,34.084921,-1.832214,1027.393633,27.310575,-5.836031e-08,97.00
2,2,1901135,174,A,2013-08-23 01:13:44.999978+00:00,1,-62.0530,150.0250,1,14.80,...,NaN,2013,8,2013,34.084947,-1.830295,1027.416777,27.310547,-1.056538e-08,97.00
3,3,1901135,174,A,2013-08-23 01:13:44.999978+00:00,1,-62.0530,150.0250,1,19.70,...,NaN,2013,8,2013,34.084970,-1.829379,1027.440425,27.310543,-3.383267e-08,97.00
4,4,1901135,174,A,2013-08-23 01:13:44.999978+00:00,1,-62.0530,150.0250,1,24.90,...,NaN,2013,8,2013,34.085011,-1.827468,1027.465505,27.310526,1.415681e-06,97.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547716,1548696,7902379,12,A,2026-06-11 07:48:48.000821+00:00,1,-58.1632,161.1366,1,1799.23,...,NaN,2026,6,2026,34.909590,1.323785,1036.152249,27.819299,5.136000e+01,98.01
1547717,1548697,7902379,12,A,2026-06-11 07:48:48.000821+00:00,1,-58.1632,161.1366,1,1849.16,...,NaN,2026,6,2026,34.906641,1.294054,1036.380011,27.819052,5.241000e+01,98.01
1547718,1548698,7902379,12,A,2026-06-11 07:48:48.000821+00:00,1,-58.1632,161.1366,1,1898.49,...,NaN,2026,6,2026,34.906706,1.233717,1036.611024,27.823347,5.351000e+01,98.01
1547719,1548699,7902379,12,A,2026-06-11 07:48:48.000821+00:00,1,-58.1632,161.1366,1,1948.77,...,NaN,2026,6,2026,34.903757,1.198325,1036.840740,27.823459,5.551000e+01,98.01
1547720,1548700,7902379,12,A,2026-06-11 07:48:48.000821+00:00,1,-58.1632,161.1366,1,2000.13,...,NaN,2026,6,2026,34.903825,1.177553,1037.075680,27.824953,5.671000e+01,98.01

## DOWNLOADING CORE FLOAT DATA

In [12]:
profiles = argo.select_profiles(lon_lim=[150,180], lat_lim=[-68,-58], 
                                      type='all')

Starting select_profiles...
Validating parameters...
Validating longitude and latitude limits...
Validating start and end dates...
Validating 'type' keyword argument...
Preparing float data for filtering...
Filtering through 20411 floats
There are 3362310 profiles associated with these floats

Sorting floats for those within the geographic range...
Creating point list from profiles...
Creating polygon...
487 floats fall within the geographic range
12389 profiles associated with those floats
Applying outside=None constraints...
Sorting floats for those within the geographic range...
Creating point list from profiles...
Creating polygon...
79 floats fall within the geographic range
2609 profiles associated with those floats
Applying outside=None constraints...
566 floats selected
14998 profiles selected according to time and space constraints
Floats Selected: dict_keys([1900148, 1900153, 1900190, 1900196, 1900343, 1900674, 1900675, 1900676, 1900805, 1900806, 1900861, 1901133, 1901135, 1901146, 1901153, 1901155, 1901157, 1901171, 1901198, 1901199, 1901386, 1901403, 1901411, 1901413, 1901415, 1901430, 1901433, 1901435, 1901438, 1901440, 1901613, 1901734, 1901758, 1901800, 1901813, 1901835, 1901838, 1902033, 1902224, 1902263, 1902265, 1902524, 1902662, 1902739, 2900108, 2900109, 2900111, 2900112, 2901303, 2901306, 2901348, 2901349, 2901350, 2901936, 2902172, 2902222, 2902228, 2902248, 2902737, 2902741, 2903454, 2903962, 2903963, 3901900, 3901904, 3901906, 3901916, 3901960, 3902129, 3902639, 3902640, 4901703, 4901792, 4902664, 4902697, 4903658, 4903845, 4903846, 5900148, 5900149, 5900214, 5900217, 5900246, 5900247, 5900248, 5900249, 5900250, 5900279, 5900321, 5900322, 5900323, 5900337, 5900340, 5900342, 5900343, 5900345, 5900346, 5900347, 5900348, 5900349, 5900458, 5900459, 5900472, 5900473, 5900475, 5900690, 5900691, 5900692, 5900694, 5900695, 5900697, 5900699, 5900790, 5900793, 5900794, 5900796, 5900807, 5900816, 5900818, 5900842, 5900844, 5900845, 5900875, 5900876, 5901103, 5901104, 5901134, 5901137, 5901138, 5901148, 5901149, 5901151, 5901152, 5901154, 5901178, 5901180, 5901199, 5901200, 5901252, 5901427, 5901429, 5901438, 5901488, 5901535, 5901554, 5901555, 5901572, 5901598, 5901599, 5901645, 5901648, 5901653, 5901654, 5901655, 5901691, 5901692, 5901693, 5901698, 5901699, 5901706, 5901849, 5901850, 5901851, 5901852, 5901853, 5901854, 5901855, 5901857, 5901964, 5901979, 5902102, 5902129, 5902338, 5902339, 5902363, 5902381, 5902382, 5902383, 5902384, 5902451, 5902452, 5902454, 5902455, 5902481, 5902482, 5902497, 5902499, 5902505, 5903230, 5903242, 5903243, 5903244, 5903245, 5903246, 5903247, 5903248, 5903249, 5903250, 5903252, 5903253, 5903254, 5903260, 5903263, 5903303, 5903315, 5903323, 5903324, 5903340, 5903408, 5903630, 5903631, 5903642, 5903643, 5903664, 5903665, 5903666, 5903667, 5903668, 5903670, 5903671, 5903672, 5903674, 5903675, 5903715, 5903716, 5903717, 5903719, 5903720, 5903721, 5903722, 5903723, 5903816, 5903817, 5903818, 5903819, 5903846, 5903847, 5903850, 5903855, 5903875, 5903876, 5903877, 5903878, 5903880, 5903881, 5903882, 5903883, 5903886, 5903926, 5903927, 5903928, 5903929, 5903931, 5903938, 5903939, 5903940, 5903941, 5904096, 5904099, 5904100, 5904101, 5904102, 5904103, 5904104, 5904105, 5904179, 5904193, 5904194, 5904195, 5904196, 5904197, 5904198, 5904199, 5904200, 5904228, 5904229, 5904230, 5904231, 5904232, 5904233, 5904234, 5904235, 5904236, 5904267, 5904368, 5904425, 5904481, 5904482, 5904483, 5904493, 5904494, 5904596, 5904597, 5904598, 5904599, 5904676, 5904677, 5904682, 5904688, 5904792, 5904797, 5904798, 5904806, 5904812, 5904818, 5904881, 5904883, 5904885, 5904886, 5904887, 5904898, 5904913, 5904919, 5904921, 5904932, 5904987, 5904997, 5904998, 5905001, 5905003, 5905004, 5905005, 5905026, 5905028, 5905031, 5905033, 5905065, 5905096, 5905097, 5905098, 5905099, 5905100, 5905101, 5905102, 5905103, 5905185, 5905186, 5905187, 5905191, 5905215, 5905216, 5905220, 5905232, 5905268, 5905372, 5905373, 5905374, 5905375, 5905376, 5905377, 5905379, 5905394, 5905396, 5905426, 5905431, 5905449, 5905450, 5905451, 5905455, 5905462, 5905516, 5905555, 5905556, 5905557, 5905559, 5905591, 5905596, 5905604, 5905638, 5905677, 5905678, 5905680, 5905690, 5905772, 5905781, 5905783, 5905786, 5905787, 5905788, 5905834, 5905877, 5905878, 5905881, 5905882, 5906138, 5906144, 5906146, 5906207, 5906221, 5906271, 5906408, 5906409, 5906410, 5906411, 5906413, 5906414, 5906442, 5906509, 5906581, 5906582, 5906583, 5906624, 5906626, 5906629, 5906912, 5906913, 5906915, 5906918, 6901004, 6901814, 6901815, 6901838, 6901842, 6901872, 6901873, 6901874, 6901880, 6901983, 6902814, 6902885, 6902891, 6902938, 6902939, 6902942, 6903184, 6903186, 6903187, 6903189, 6903190, 6903205, 6903206, 6903210, 6903211, 6903212, 6903213, 6903229, 6903230, 6903231, 6903232, 6903233, 6903251, 6903253, 6903254, 6903768, 6903769, 6903770, 6903771, 6903777, 6903790, 6903791, 6903808, 6903809, 6903814, 6903829, 6903830, 6990587, 7900065, 7900066, 7900067, 7900121, 7900208, 7900209, 7900210, 7900306, 7900307, 7900308, 7900309, 7900315, 7900316, 7900318, 7900323, 7900324, 7900325, 7900326, 7900327, 7900328, 7900332, 7900336, 7900390, 7900391, 7900393, 7900515, 7900609, 7900611, 7900618, 7900621, 7900622, 7900623, 7900625, 7900626, 7900631, 7900635, 7900636, 7900637, 7900648, 7900649, 7900650, 7900651, 7900658, 7900659, 7900667, 7900668, 7900669, 7900680, 7900681, 7900682, 7900683, 7900684, 7900686, 7900687, 7900688, 7900689, 7900690, 7900694, 7900705, 7900793, 7900794, 7900795, 7900796, 7900797, 7900798, 7900799, 7900800, 7900801, 7900802, 7900803, 7900805, 7900806, 7900807, 7900808, 7900809, 7900810, 7900811, 7900812, 7900868, 7900870, 7900876, 7900891, 7900895, 7900896, 7900900, 7900905, 7900908, 7900909, 7900920, 7900922, 7900930, 7900931, 7900932, 7900933, 7900937, 7900938, 7900950, 7902154, 7902155, 7902207, 7902208, 7902209, 7902210, 7902211, 7902212, 7902256, 7902257, 7902258, 7902259, 7902379])

In [13]:
df = argo.load_float_data(profiles, variables=['TEMP','PSAL'])

Validating passed floats...
Validating passed 'variables'...
1900148_prof.nc needs to be downloaded.
Downloading 1900148_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1900148/1900148_prof.nc...
Success!
1900153_prof.nc needs to be downloaded.
Downloading 1900153_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1900153/1900153_prof.nc...
Success!
1900190_prof.nc needs to be downloaded.
Downloading 1900190_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1900190/1900190_prof.nc...
Success!
1900196_prof.nc needs to be downloaded.
Downloading 1900196_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1900196/1900196_prof.nc...
Success!
1900343_prof.nc needs to be downloaded.
Downloading 1900343_prof.nc from https://data-argo.ifremer.fr/dac/bodc/1900343/1900343_prof.nc...
Success!
1900674_prof.nc needs to be downloaded.
Downloading 1900674_prof.nc from https://data-argo.ifremer.fr/dac/jma/1900674/1900674_prof.nc...
Success!
1900675_prof.nc needs to be downloaded.
Downloading 1900675_prof.nc from https://data-argo.ifremer.fr/dac/jma/1900675/1900675_prof.nc...
Success!
1900676_prof.nc needs to be downloaded.
Downloading 1900676_prof.nc from https://data-argo.ifremer.fr/dac/jma/1900676/1900676_prof.nc...
Success!
1900805_prof.nc needs to be downloaded.
Downloading 1900805_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1900805/1900805_prof.nc...
Success!
1900806_prof.nc needs to be downloaded.
Downloading 1900806_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1900806/1900806_prof.nc...
Success!
1900861_prof.nc needs to be downloaded.
Downloading 1900861_prof.nc from https://data-argo.ifremer.fr/dac/coriolis/1900861/1900861_prof.nc...
Success!
1901133_prof.nc needs to be downloaded.
Downloading 1901133_prof.nc from https://data-argo.ifremer.fr/dac/csiro/1901133/1901133_prof.nc...
Success!
1901135_Sprof.nc does not need to be updated yet.
1901146_prof.nc needs to be downloaded.
Downloading 1901146_prof.nc from https://data-argo.ifremer.fr/dac/csiro/1901146/1901146_prof.nc...
Success!
1901153_Sprof.nc does not need to be updated yet.
1901155_Sprof.nc does not need to be updated yet.
1901157_Sprof.nc does not need to be updated yet.
1901171_prof.nc needs to be downloaded.
Downloading 1901171_prof.nc from https://data-argo.ifremer.fr/dac/coriolis/1901171/1901171_prof.nc...
Success!
1901198_prof.nc needs to be downloaded.
Downloading 1901198_prof.nc from https://data-argo.ifremer.fr/dac/coriolis/1901198/1901198_prof.nc...
Success!
1901199_prof.nc needs to be downloaded.
Downloading 1901199_prof.nc from https://data-argo.ifremer.fr/dac/coriolis/1901199/1901199_prof.nc...
Success!
1901386_prof.nc needs to be downloaded.
Downloading 1901386_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901386/1901386_prof.nc...
Success!
1901403_prof.nc needs to be downloaded.
Downloading 1901403_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901403/1901403_prof.nc...
Success!
1901411_prof.nc needs to be downloaded.
Downloading 1901411_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901411/1901411_prof.nc...
Success!
1901413_prof.nc needs to be downloaded.
Downloading 1901413_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901413/1901413_prof.nc...
Success!
1901415_prof.nc needs to be downloaded.
Downloading 1901415_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901415/1901415_prof.nc...
Success!
1901430_prof.nc needs to be downloaded.
Downloading 1901430_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901430/1901430_prof.nc...
Success!
1901433_prof.nc needs to be downloaded.
Downloading 1901433_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901433/1901433_prof.nc...
Success!
1901435_prof.nc needs to be downloaded.
Downloading 1901435_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901435/1901435_prof.nc...
Success!
1901438_prof.nc needs to be downloaded.
Downloading 1901438_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901438/1901438_prof.nc...
Success!
1901440_prof.nc needs to be downloaded.
Downloading 1901440_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901440/1901440_prof.nc...
Success!
1901613_prof.nc needs to be downloaded.
Downloading 1901613_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901613/1901613_prof.nc...
Success!
1901734_prof.nc needs to be downloaded.
Downloading 1901734_prof.nc from https://data-argo.ifremer.fr/dac/csiro/1901734/1901734_prof.nc...
Success!
1901758_prof.nc needs to be downloaded.
Downloading 1901758_prof.nc from https://data-argo.ifremer.fr/dac/csiro/1901758/1901758_prof.nc...
Success!
1901800_prof.nc needs to be downloaded.
Downloading 1901800_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901800/1901800_prof.nc...
Success!
1901813_prof.nc needs to be downloaded.
Downloading 1901813_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901813/1901813_prof.nc...
Success!
1901835_prof.nc needs to be downloaded.
Downloading 1901835_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901835/1901835_prof.nc...
Success!
1901838_prof.nc needs to be downloaded.
Downloading 1901838_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1901838/1901838_prof.nc...
Success!
1902033_prof.nc needs to be downloaded.
Downloading 1902033_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1902033/1902033_prof.nc...
Success!
1902224_prof.nc needs to be downloaded.
Downloading 1902224_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1902224/1902224_prof.nc...
Success!
1902263_prof.nc needs to be downloaded.
Downloading 1902263_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1902263/1902263_prof.nc...
Success!
1902265_prof.nc needs to be downloaded.
Downloading 1902265_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1902265/1902265_prof.nc...
Success!
1902524_prof.nc needs to be downloaded.
Downloading 1902524_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1902524/1902524_prof.nc...
Success!
Updating 1902662_Sprof.nc...
Downloading 1902662_Sprof.nc from https://data-argo.ifremer.fr/dac/coriolis/1902662/1902662_Sprof.nc...
Success!
1902739_prof.nc needs to be downloaded.
Downloading 1902739_prof.nc from https://data-argo.ifremer.fr/dac/aoml/1902739/1902739_prof.nc...
Success!
2900108_prof.nc needs to be downloaded.
Downloading 2900108_prof.nc from https://data-argo.ifremer.fr/dac/aoml/2900108/2900108_prof.nc...
Success!
2900109_prof.nc needs to be downloaded.
Downloading 2900109_prof.nc from https://data-argo.ifremer.fr/dac/aoml/2900109/2900109_prof.nc...
Success!
2900111_prof.nc needs to be downloaded.
Downloading 2900111_prof.nc from https://data-argo.ifremer.fr/dac/aoml/2900111/2900111_prof.nc...
Success!
2900112_prof.nc needs to be downloaded.
Downloading 2900112_prof.nc from https://data-argo.ifremer.fr/dac/aoml/2900112/2900112_prof.nc...
Success!
2901303_prof.nc needs to be downloaded.
Downloading 2901303_prof.nc from https://data-argo.ifremer.fr/dac/incois/2901303/2901303_prof.nc...
Success!
2901306_prof.nc needs to be downloaded.
Downloading 2901306_prof.nc from https://data-argo.ifremer.fr/dac/incois/2901306/2901306_prof.nc...
Success!
2901348_prof.nc needs to be downloaded.
Downloading 2901348_prof.nc from https://data-argo.ifremer.fr/dac/incois/2901348/2901348_prof.nc...
Success!
2901349_prof.nc needs to be downloaded.
Downloading 2901349_prof.nc from https://data-argo.ifremer.fr/dac/incois/2901349/2901349_prof.nc...
Success!
2901350_prof.nc needs to be downloaded.
Downloading 2901350_prof.nc from https://data-argo.ifremer.fr/dac/incois/2901350/2901350_prof.nc...
Success!
Updating 2901936_Sprof.nc...
Downloading 2901936_Sprof.nc from https://data-argo.ifremer.fr/dac/bodc/2901936/2901936_Sprof.nc...
Success!
2902172_prof.nc needs to be downloaded.
Downloading 2902172_prof.nc from https://data-argo.ifremer.fr/dac/incois/2902172/2902172_prof.nc...
Success!
2902222_prof.nc needs to be downloaded.
Downloading 2902222_prof.nc from https://data-argo.ifremer.fr/dac/incois/2902222/2902222_prof.nc...
Success!
2902228_prof.nc needs to be downloaded.
Downloading 2902228_prof.nc from https://data-argo.ifremer.fr/dac/incois/2902228/2902228_prof.nc...
Success!
2902248_prof.nc needs to be downloaded.
Downloading 2902248_prof.nc from https://data-argo.ifremer.fr/dac/incois/2902248/2902248_prof.nc...
Success!
2902737_prof.nc needs to be downloaded.
Downloading 2902737_prof.nc from https://data-argo.ifremer.fr/dac/csio/2902737/2902737_prof.nc...
Success!
2902741_prof.nc needs to be downloaded.
Downloading 2902741_prof.nc from https://data-argo.ifremer.fr/dac/csio/2902741/2902741_prof.nc...
Success!
2903454_Sprof.nc does not need to be updated yet.
2903962_prof.nc needs to be downloaded.
Downloading 2903962_prof.nc from https://data-argo.ifremer.fr/dac/aoml/2903962/2903962_prof.nc...
Success!
2903963_prof.nc needs to be downloaded.
Downloading 2903963_prof.nc from https://data-argo.ifremer.fr/dac/aoml/2903963/2903963_prof.nc...
Success!
3901900_prof.nc needs to be downloaded.
Downloading 3901900_prof.nc from https://data-argo.ifremer.fr/dac/bodc/3901900/3901900_prof.nc...
Success!
3901904_prof.nc needs to be downloaded.
Downloading 3901904_prof.nc from https://data-argo.ifremer.fr/dac/bodc/3901904/3901904_prof.nc...
Success!
3901906_prof.nc needs to be downloaded.
Downloading 3901906_prof.nc from https://data-argo.ifremer.fr/dac/bodc/3901906/3901906_prof.nc...
Success!
3901916_prof.nc needs to be downloaded.
Downloading 3901916_prof.nc from https://data-argo.ifremer.fr/dac/bodc/3901916/3901916_prof.nc...
Success!
3901960_prof.nc needs to be downloaded.
Downloading 3901960_prof.nc from https://data-argo.ifremer.fr/dac/bodc/3901960/3901960_prof.nc...
Success!
3902129_Sprof.nc does not need to be updated yet.
3902639_prof.nc needs to be downloaded.
Downloading 3902639_prof.nc from https://data-argo.ifremer.fr/dac/aoml/3902639/3902639_prof.nc...
Success!
3902640_prof.nc needs to be downloaded.
Downloading 3902640_prof.nc from https://data-argo.ifremer.fr/dac/aoml/3902640/3902640_prof.nc...
Success!
4901703_prof.nc needs to be downloaded.
Downloading 4901703_prof.nc from https://data-argo.ifremer.fr/dac/aoml/4901703/4901703_prof.nc...
Success!
4901792_prof.nc needs to be downloaded.
Downloading 4901792_prof.nc from https://data-argo.ifremer.fr/dac/meds/4901792/4901792_prof.nc...
Success!
4902664_prof.nc needs to be downloaded.
Downloading 4902664_prof.nc from https://data-argo.ifremer.fr/dac/meds/4902664/4902664_prof.nc...
Success!
4902697_prof.nc needs to be downloaded.
Downloading 4902697_prof.nc from https://data-argo.ifremer.fr/dac/meds/4902697/4902697_prof.nc...
Success!
Updating 4903658_Sprof.nc...
Downloading 4903658_Sprof.nc from https://data-argo.ifremer.fr/dac/coriolis/4903658/4903658_Sprof.nc...
Success!
4903845_prof.nc needs to be downloaded.
Downloading 4903845_prof.nc from https://data-argo.ifremer.fr/dac/aoml/4903845/4903845_prof.nc...
Success!
4903846_prof.nc needs to be downloaded.
Downloading 4903846_prof.nc from https://data-argo.ifremer.fr/dac/aoml/4903846/4903846_prof.nc...
Success!
5900148_prof.nc needs to be downloaded.
Downloading 5900148_prof.nc from https://data-argo.ifremer.fr/dac/jma/5900148/5900148_prof.nc...
Success!
5900149_prof.nc needs to be downloaded.
Downloading 5900149_prof.nc from https://data-argo.ifremer.fr/dac/jma/5900149/5900149_prof.nc...
Success!
5900214_prof.nc needs to be downloaded.
Downloading 5900214_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900214/5900214_prof.nc...
Success!
5900217_prof.nc needs to be downloaded.
Downloading 5900217_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900217/5900217_prof.nc...
Success!
5900246_prof.nc needs to be downloaded.
Downloading 5900246_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900246/5900246_prof.nc...
Success!
5900247_prof.nc needs to be downloaded.
Downloading 5900247_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900247/5900247_prof.nc...
Success!
5900248_prof.nc needs to be downloaded.
Downloading 5900248_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900248/5900248_prof.nc...
Success!
5900249_prof.nc needs to be downloaded.
Downloading 5900249_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900249/5900249_prof.nc...
Success!
5900250_prof.nc needs to be downloaded.
Downloading 5900250_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900250/5900250_prof.nc...
Success!
5900279_prof.nc needs to be downloaded.
Downloading 5900279_prof.nc from https://data-argo.ifremer.fr/dac/jma/5900279/5900279_prof.nc...
Success!
5900321_prof.nc needs to be downloaded.
Downloading 5900321_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900321/5900321_prof.nc...
Success!
5900322_prof.nc needs to be downloaded.
Downloading 5900322_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900322/5900322_prof.nc...
Success!
5900323_prof.nc needs to be downloaded.
Downloading 5900323_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900323/5900323_prof.nc...
Success!
5900337_prof.nc needs to be downloaded.
Downloading 5900337_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900337/5900337_prof.nc...
Success!
5900340_prof.nc needs to be downloaded.
Downloading 5900340_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900340/5900340_prof.nc...
Success!
5900342_prof.nc needs to be downloaded.
Downloading 5900342_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900342/5900342_prof.nc...
Success!
5900343_prof.nc needs to be downloaded.
Downloading 5900343_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900343/5900343_prof.nc...
Success!
5900345_Sprof.nc does not need to be updated yet.
5900346_prof.nc needs to be downloaded.
Downloading 5900346_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900346/5900346_prof.nc...
Success!
5900347_prof.nc needs to be downloaded.
Downloading 5900347_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900347/5900347_prof.nc...
Success!
5900348_prof.nc needs to be downloaded.
Downloading 5900348_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900348/5900348_prof.nc...
Success!
5900349_prof.nc needs to be downloaded.
Downloading 5900349_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900349/5900349_prof.nc...
Success!
5900458_prof.nc needs to be downloaded.
Downloading 5900458_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900458/5900458_prof.nc...
Success!
5900459_prof.nc needs to be downloaded.
Downloading 5900459_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900459/5900459_prof.nc...
Success!
5900472_prof.nc needs to be downloaded.
Downloading 5900472_prof.nc from https://data-argo.ifremer.fr/dac/kiost/5900472/5900472_prof.nc...
Success!
5900473_prof.nc needs to be downloaded.
Downloading 5900473_prof.nc from https://data-argo.ifremer.fr/dac/kiost/5900473/5900473_prof.nc...
Success!
5900475_prof.nc needs to be downloaded.
Downloading 5900475_prof.nc from https://data-argo.ifremer.fr/dac/kiost/5900475/5900475_prof.nc...
Success!
5900690_prof.nc needs to be downloaded.
Downloading 5900690_prof.nc from https://data-argo.ifremer.fr/dac/kiost/5900690/5900690_prof.nc...
Success!
5900691_prof.nc needs to be downloaded.
Downloading 5900691_prof.nc from https://data-argo.ifremer.fr/dac/kiost/5900691/5900691_prof.nc...
Success!
5900692_prof.nc needs to be downloaded.
Downloading 5900692_prof.nc from https://data-argo.ifremer.fr/dac/kiost/5900692/5900692_prof.nc...
Success!
5900694_prof.nc needs to be downloaded.
Downloading 5900694_prof.nc from https://data-argo.ifremer.fr/dac/kiost/5900694/5900694_prof.nc...
Success!
5900695_prof.nc needs to be downloaded.
Downloading 5900695_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900695/5900695_prof.nc...
Success!
5900697_prof.nc needs to be downloaded.
Downloading 5900697_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900697/5900697_prof.nc...
Success!
5900699_prof.nc needs to be downloaded.
Downloading 5900699_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5900699/5900699_prof.nc...
Success!
5900790_prof.nc needs to be downloaded.
Downloading 5900790_prof.nc from https://data-argo.ifremer.fr/dac/jma/5900790/5900790_prof.nc...
Success!
5900793_prof.nc needs to be downloaded.
Downloading 5900793_prof.nc from https://data-argo.ifremer.fr/dac/jma/5900793/5900793_prof.nc...
Success!
5900794_prof.nc needs to be downloaded.
Downloading 5900794_prof.nc from https://data-argo.ifremer.fr/dac/jma/5900794/5900794_prof.nc...
Success!
5900796_prof.nc needs to be downloaded.
Downloading 5900796_prof.nc from https://data-argo.ifremer.fr/dac/jma/5900796/5900796_prof.nc...
Success!
5900807_prof.nc needs to be downloaded.
Downloading 5900807_prof.nc from https://data-argo.ifremer.fr/dac/jma/5900807/5900807_prof.nc...
Success!
5900816_prof.nc needs to be downloaded.
Downloading 5900816_prof.nc from https://data-argo.ifremer.fr/dac/jma/5900816/5900816_prof.nc...
Success!
5900818_prof.nc needs to be downloaded.
Downloading 5900818_prof.nc from https://data-argo.ifremer.fr/dac/jma/5900818/5900818_prof.nc...
Success!
5900842_prof.nc needs to be downloaded.
Downloading 5900842_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900842/5900842_prof.nc...
Success!
5900844_prof.nc needs to be downloaded.
Downloading 5900844_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900844/5900844_prof.nc...
Success!
5900845_prof.nc needs to be downloaded.
Downloading 5900845_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900845/5900845_prof.nc...
Success!
5900875_prof.nc needs to be downloaded.
Downloading 5900875_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900875/5900875_prof.nc...
Success!
5900876_prof.nc needs to be downloaded.
Downloading 5900876_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5900876/5900876_prof.nc...
Success!
5901103_prof.nc needs to be downloaded.
Downloading 5901103_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5901103/5901103_prof.nc...
Success!
5901104_prof.nc needs to be downloaded.
Downloading 5901104_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5901104/5901104_prof.nc...
Success!
5901134_prof.nc needs to be downloaded.
Downloading 5901134_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5901134/5901134_prof.nc...
Success!
5901137_prof.nc needs to be downloaded.
Downloading 5901137_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5901137/5901137_prof.nc...
Success!
5901138_prof.nc needs to be downloaded.
Downloading 5901138_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5901138/5901138_prof.nc...
Success!
5901148_prof.nc needs to be downloaded.
Downloading 5901148_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5901148/5901148_prof.nc...
Success!
5901149_prof.nc needs to be downloaded.
Downloading 5901149_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5901149/5901149_prof.nc...
Success!
5901151_prof.nc needs to be downloaded.
Downloading 5901151_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5901151/5901151_prof.nc...
Success!
5901152_prof.nc needs to be downloaded.
Downloading 5901152_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5901152/5901152_prof.nc...
Success!
5901154_prof.nc needs to be downloaded.
Downloading 5901154_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5901154/5901154_prof.nc...
Success!
5901178_Sprof.nc does not need to be updated yet.
5901180_prof.nc needs to be downloaded.
Downloading 5901180_prof.nc from https://data-argo.ifremer.fr/dac/csiro/5901180/5901180_prof.nc...
Success!
5901199_prof.nc needs to be downloaded.
Downloading 5901199_prof.nc from https://data-argo.ifremer.fr/dac/jma/5901199/5901199_prof.nc...
Success!
5901200_prof.nc needs to be downloaded.
Downloading 5901200_prof.nc from https://data-argo.ifremer.fr/dac/jma/5901200/5901200_prof.nc...
Success!
5901252_prof.nc needs to be downloaded.
Downloading 5901252_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5901252/5901252_prof.nc...
Success!
5901427_prof.nc needs to be downloaded.
Downloading 5901427_prof.nc from https://data-argo.ifremer.fr/dac/aoml/5901427/5901427_prof.nc...
Success!
5901429_prof.nc needs to be downloaded.

TypeError: unsupported type for timedelta days component: MaskedConstant

In [14]:
df.to_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new_unedited_CORE_profiles_BR_extended_area_all_time.csv', index = 'False')
# df.to_csv('/Users/steviewalker/Documents/IBIS_Project/Data_Summer/new_bgc_profiles_BR_extended_area_all_time.csv', index = 'False')

## Convert to datetime, add month, year, season, MLP and physical variable columns (absolute salinity, conservative temperaure, potential density, in situ density, and buoyancy frequency

In [16]:
df_core = pd.read_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new_unedited_CORE_profiles_BR_extended_area_all_time.csv')

/var/folders/sr/nn_fjjln6s33md98tyfc3rd40000gn/T/ipykernel_73723/3830893039.py:1: DtypeWarning: Columns (0: season) have mixed types. Specify dtype option on import or set low_memory=False.
  df_core = pd.read_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new_unedited_CORE_profiles_BR_extended_area_all_time.csv')

In [17]:
# NEW DATA

#convert to datetime
df_core['DATE'] = pd.to_datetime(df_core['DATE'],format = 'mixed',utc=True)
df_core = df_core.dropna(subset=["DATE"]) #drop any cycles with no date or lat/lon 

#fix lat lon values with '--' (replace with nan) 
df_core['LATITUDE'] = pd.to_numeric(df_core['LATITUDE'], errors='coerce')
df_core['LONGITUDE'] = pd.to_numeric(df_core['LONGITUDE'], errors='coerce')

In [18]:
#create season columns
df_core["year"] = df_core["DATE"].dt.year.astype("Int64")
df_core["month"] = df_core["DATE"].dt.month.astype("Int64")

def assign_season(row):
    m = int(row["month"])
    y = int(row["year"])
    if m >= 9:
        return f"{y}-{y+1}"
    elif m <= 4:
        return f"{y-1}-{y}"
    else:
        return f"{y}"

df_core["season"] = df_core.apply(assign_season, axis=1)

In [19]:
# define function for calculating SA, CT, potential dens, in-situ dens, buoyancy frequency
def calc_phys_vars(df):
        
    # Columns needed
    cols = ['PSAL_ADJUSTED','TEMP_ADJUSTED' ,'PRES_ADJUSTED', 'LATITUDE', 'LONGITUDE']
    
    # only do calculation on good qc T and S data - create nan values where not good data
    qc_flags = [1,2,5,8]
    mask_qc = df['PSAL_ADJUSTED_QC'].isin(qc_flags) & df['TEMP_ADJUSTED_QC'].isin(qc_flags)
    df['PSAL_ADJUSTED'] = df['PSAL_ADJUSTED'].where(mask_qc)
    df['TEMP_ADJUSTED'] = df['TEMP_ADJUSTED'].where(mask_qc)    
    
    # mask valid (non-null) rows
    mask = df[cols].notnull().all(axis=1)
    
    # initialize outputs as NaN
    SA = np.full(len(df), np.nan)
    CT = np.full(len(df), np.nan)
    rho = np.full(len(df), np.nan)
    sigma0 = np.full(len(df), np.nan)
    nsq = np.full(len(df), np.nan)
    
    # extract numeric arrays for valid rows
    SP = df.loc[mask, 'PSAL_ADJUSTED'].astype(float).to_numpy()
    PT = df.loc[mask, 'TEMP_ADJUSTED'].astype(float).to_numpy()
    pres = df.loc[mask, 'PRES_ADJUSTED'].astype(float).to_numpy()
    LAT = df.loc[mask, 'LATITUDE'].astype(float).to_numpy()
    LON = df.loc[mask, 'LONGITUDE'].astype(float).to_numpy()
    
    # calculate variables using gsw
    SA_valid = gsw.SA_from_SP(SP=SP, p=pres, lon=LON, lat=LAT)
    CT_valid = gsw.CT_from_t(SA=SA_valid, t=PT, p=pres)
    rho_valid = gsw.rho(SA=SA_valid, CT=CT_valid, p=pres)
    sigma0_valid = gsw.sigma0(SA=SA_valid, CT=CT_valid)
    nsq_valid = gsw.Nsquared(SA=SA_valid, CT=CT_valid, p=pres,lat=LAT)
    
    # store back into full-length arrays
    SA[mask] = SA_valid
    CT[mask] = CT_valid
    rho[mask] = rho_valid
    sigma0[mask] = sigma0_valid
    np.putmask(nsq, mask, nsq_valid) # found on stack overflow because nsq was 2 dimensional so previous method wasn't working
    
    # sdd results to the dataframe
    df = df.copy()
    df['SA'] = SA
    df['CT'] = CT
    df['rho'] = rho
    df['sigma0'] = sigma0
    df['nsq'] = nsq
    
    return df

df_edited = calc_phys_vars(df_core)

In [20]:
def calc_mlp_density(df_profile, delta_sigma=0.03):
    #calc MLD for a single profile using density threshold
    df_profile = df_profile.sort_values('PRES_ADJUSTED')

    # get SA, CT, and potential density values
    SA = df_profile['SA']
    CT = df_profile['CT']
    sigma0 = df_profile['sigma0']

    sigma_surface = sigma0.iloc[0]
    d_sigma = sigma0 - sigma_surface

    # find first depth where density difference exceeds threshold
    idx = np.argmax(d_sigma > delta_sigma)
    if d_sigma.iloc[idx] <= delta_sigma:
        return np.nan  # no threshold reached
    return df_profile['PRES_ADJUSTED'].iloc[idx]

mld = (df_edited.groupby(['WMOID', 'CYCLE_NUMBER']).apply(calc_mlp_density).reset_index(name='MLP'))
df_full_edited = df_edited.merge(mld, on=['WMOID', 'CYCLE_NUMBER'], how='left')

In [21]:
df_full_edited

,Unnamed: 0.1,Unnamed: 0,WMOID,CYCLE_NUMBER,DIRECTION,DATE,DATE_QC,LATITUDE,LONGITUDE,POSITION_QC,...,DOWNWELLING_PAR_ADJUSTED_ERROR,year,month,season,SA,CT,rho,sigma0,nsq,MLP
0,0,0,1901135,174,A,2013-08-23 01:13:44.999978+00:00,1,-62.0530,150.0250,1,...,NaN,2013,8,2013,34.084945,-1.831148,1027.374795,27.310568,1.905520e-08,97.00
1,1,1,1901135,174,A,2013-08-23 01:13:44.999978+00:00,1,-62.0530,150.0250,1,...,NaN,2013,8,2013,34.084921,-1.832214,1027.393633,27.310575,-5.836031e-08,97.00
2,2,2,1901135,174,A,2013-08-23 01:13:44.999978+00:00,1,-62.0530,150.0250,1,...,NaN,2013,8,2013,34.084947,-1.830295,1027.416777,27.310547,-1.056538e-08,97.00
3,3,3,1901135,174,A,2013-08-23 01:13:44.999978+00:00,1,-62.0530,150.0250,1,...,NaN,2013,8,2013,34.084970,-1.829379,1027.440425,27.310543,-3.383267e-08,97.00
4,4,4,1901135,174,A,2013-08-23 01:13:44.999978+00:00,1,-62.0530,150.0250,1,...,NaN,2013,8,2013,34.085011,-1.827468,1027.465505,27.310526,1.415681e-06,97.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547716,1548696,1548696,7902379,12,A,2026-06-11 07:48:48.000821+00:00,1,-58.1632,161.1366,1,...,NaN,2026,6,2026,34.909590,1.323785,1036.152249,27.819299,5.136000e+01,98.01
1547717,1548697,1548697,7902379,12,A,2026-06-11 07:48:48.000821+00:00,1,-58.1632,161.1366,1,...,NaN,2026,6,2026,34.906641,1.294054,1036.380011,27.819052,5.241000e+01,98.01
1547718,1548698,1548698,7902379,12,A,2026-06-11 07:48:48.000821+00:00,1,-58.1632,161.1366,1,...,NaN,2026,6,2026,34.906706,1.233717,1036.611024,27.823347,5.351000e+01,98.01
1547719,1548699,1548699,7902379,12,A,2026-06-11 07:48:48.000821+00:00,1,-58.1632,161.1366,1,...,NaN,2026,6,2026,34.903757,1.198325,1036.840740,27.823459,5.551000e+01,98.01
1547720,1548700,1548700,7902379,12,A,2026-06-11 07:48:48.000821+00:00,1,-58.1632,161.1366,1,...,NaN,2026,6,2026,34.903825,1.177553,1037.075680,27.824953,5.671000e+01,98.01

In [22]:
df_full_edited.to_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new_CORE_profiles_ext_alltime.csv', index = 'False')

# df_full_edited.to_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/new_bgc_profiles_BR_extended_area_all_time.csv', index = 'False')

## EasyOneArgo Data

## BGC data

In [14]:
def parse_argo_csv(filepath):
    float_id = None
    profile_number = None
    profile_date = None
    header_line_idx = None

    with open(filepath, "r") as f:
        lines = f.readlines()

    for i, line in enumerate(lines): # add elif lines for lat/lon
        if line.startswith("#platform_number"):
            float_id = line.split("=")[1].strip()
        elif line.startswith("#cycle_number"):
            profile_number = int(line.split("=")[1].strip())
        elif line.startswith("#profile_date"):
            profile_date = line.split("=")[1].strip()
        elif not line.startswith("#"):
            header_line_idx = i
            break

    df = pd.read_csv(filepath, skiprows=header_line_idx)

    # Strip units in parentheses from column names
    df.columns = [re.sub(r"\s*\(.*?\)", "", col).strip() for col in df.columns]

    df["float_id"] = float_id
    df["profile_number"] = profile_number
    df["profile_date"] = pd.to_datetime(profile_date)
    # add columns for lat/lon

    return df

# Example: one float
# df = parse_argo_csv(filepath = '/Users/steviewalker/Documents/Argo/EasyOneArgoBGCLite/EasyOneArgoBGCLite_20260914T035253Z/data/5905062/5905062_001_EasyBGCLite.csv')
df = parse_argo_csv(filepath = '/Users/lilah/Documents/IBIS_Project/Data_Summer/EasyOneArgoBGCLite_20260914T035253Z/data/5905103/5905103_001_EasyBGCLite.csv')

# print(df.columns.tolist())

['pressure', 'temperature', 'salinity', 'oxygen', 'nitrate', 'pH', 'chla', 'chlaFluorescence', 'bbp700', 'downIrr380', 'downIrr412', 'downIrr443', 'downIrr490', 'downIrr555', 'downwellingPar', 'pressure_error', 'temperature_error', 'salinity_error', 'oxygen_error', 'nitrate_error', 'pH_error', 'chla_error', 'chlaFluorescence_error', 'bbp700_error', 'downIrr380_error', 'downIrr412_error', 'downIrr443_error', 'downIrr490_error', 'downIrr555_error', 'downwellingPar_error', 'float_id', 'profile_number', 'profile_date']

In [15]:
import glob
import os

def combine_float_profiles(folder_path, output_path=None):
    csv_files = sorted(glob.glob(os.path.join(folder_path, "*_EasyBGCLite.csv")))

    if not csv_files:
        raise FileNotFoundError(f"No matching CSV files found in {folder_path}")

    dfs = [parse_argo_csv(f) for f in csv_files]
    combined = pd.concat(dfs, ignore_index=True)

    # Sort by profile number so profiles are in order
    combined = combined.sort_values("profile_number").reset_index(drop=True)

    if output_path:
        combined.to_csv(output_path, index=False)

    return combined

# Example: combine all profiles for float 5905062
# folder = '/Users/steviewalker/Documents/Argo/EasyOneArgoBGCLite/EasyOneArgoBGCLite_20260914T035253Z/data/5905104'
folder = '/Users/lilah/Documents/IBIS_Project/Data_Summer/EasyOneArgoBGCLite_20260914T035253Z/data/5905103'
combined = combine_float_profiles(folder, output_path=os.path.join(folder, "5905103_combined.csv"))

print(combined.shape)
print(combined["profile_number"].unique())

(12639, 33)
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157]

In [16]:
combined

,pressure,temperature,salinity,oxygen,nitrate,pH,chla,chlaFluorescence,bbp700,downIrr380,...,bbp700_error,downIrr380_error,downIrr412_error,downIrr443_error,downIrr490_error,downIrr555_error,downwellingPar_error,float_id,profile_number,profile_date
0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5905103,1,2018-02-16 12:31:57+00:00
1,320.0,2.107,34.292,212.934,34.606,NaN,0.0011,0.0072,0.000526,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5905103,1,2018-02-16 12:31:57+00:00
2,310.0,2.002,34.269,217.730,34.398,NaN,0.0011,0.0072,0.000514,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5905103,1,2018-02-16 12:31:57+00:00
3,300.0,1.883,34.243,225.218,34.091,NaN,0.0011,0.0072,0.000495,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5905103,1,2018-02-16 12:31:57+00:00
4,290.0,1.795,34.221,232.432,33.899,NaN,0.0011,0.0072,0.000491,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5905103,1,2018-02-16 12:31:57+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12634,115.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5905103,157,2022-05-31 08:50:42+00:00
12635,110.0,1.860,33.991,300.559,NaN,NaN,0.0857,0.3698,0.000641,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5905103,157,2022-05-31 08:50:42+00:00
12636,105.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5905103,157,2022-05-31 08:50:42+00:00
12637,90.0,1.730,33.907,316.752,NaN,NaN,0.1301,0.5616,0.000672,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5905103,157,2022-05-31 08:50:42+00:00
12638,1400.0,1.914,34.711,185.899,NaN,NaN,0.0017,0.0072,0.000234,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5905103,157,2022-05-31 08:50:42+00:00

In [18]:
combined.to_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/EasyOneArgoBGCLite_5905103.csv', index = 'False')

In [25]:
# NEW DATA

#convert to datetime
df['DATE'] = pd.to_datetime(df['DATE'],format = 'mixed',utc=True)
df = df.dropna(subset=["DATE"]) #drop any cycles with no date or lat/lon 

#fix lat lon values with '--' (replace with nan) 
df['LATITUDE'] = pd.to_numeric(df['LATITUDE'], errors='coerce')
df['LONGITUDE'] = pd.to_numeric(df['LONGITUDE'], errors='coerce')

TypeError: 'TarFile' object is not subscriptable

In [ ]:
#create season columns
df["year"] = df["DATE"].dt.year.astype("Int64")
df["month"] = df["DATE"].dt.month.astype("Int64")

def assign_season(row):
    m = int(row["month"])
    y = int(row["year"])
    if m >= 9:
        return f"{y}-{y+1}"
    elif m <= 4:
        return f"{y-1}-{y}"
    else:
        return f"{y}"

df["season"] = df.apply(assign_season, axis=1)

## TS data

In [ ]:
df = pd.read_csv('/Users/lilah/Documents/IBIS_Project/Data_Summer/EasyOneArgoTSLite.tar')

In [ ]:
# NEW DATA

#convert to datetime
df['DATE'] = pd.to_datetime(df['DATE'],format = 'mixed',utc=True)
df = df.dropna(subset=["DATE"]) #drop any cycles with no date or lat/lon 

#fix lat lon values with '--' (replace with nan) 
df['LATITUDE'] = pd.to_numeric(df['LATITUDE'], errors='coerce')
df['LONGITUDE'] = pd.to_numeric(df['LONGITUDE'], errors='coerce')

In [ ]:
#create season columns
df["year"] = df["DATE"].dt.year.astype("Int64")
df["month"] = df["DATE"].dt.month.astype("Int64")

def assign_season(row):
    m = int(row["month"])
    y = int(row["year"])
    if m >= 9:
        return f"{y}-{y+1}"
    elif m <= 4:
        return f"{y-1}-{y}"
    else:
        return f"{y}"

df["season"] = df.apply(assign_season, axis=1)